name: SBI csv police for transform
on:
  pull_request:
    types:
      - opened
    branches:
      - Eigo-Mt-Fuji-patch-1
    paths:
      - downloads/sbi/*.csv
jobs:
  sbi-csv-police:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Transform original SBI csv file 
        run: |
          # export csv destination path
          export PROCESSED_CSV_DEST_PATH=$(pwd)/src/data/fx_transactions/
          echo $PROCESSED_CSV_DEST_PATH

          ls -la downloads/sbi/*.csv

          find $(pwd)/downloads/sbi -name '*.csv' | sort | xargs -ITARGET sh -c "cd scripts && python transform-sbi-csv.py TARGET $PROCESSED_CSV_DEST_PATH && rm -rf TARGET"
        working-directory: ./

      - name: Get current datetime
        id: datetime
        run: echo "::set-output name=value::$(date +'%Y-%m-%d %H:%M:%S')"

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'src/data/fx_transactions/*'
          remove: './downloads/sbi/*.csv'
          message: Update src/data/fx_transactions ${{ steps.datetime.outputs.value }}
          default_author: Eigo-Mt-Fuji
          author_name: Eigo-Mt-Fuji
          author_email: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit: --signoff
          committer_name: Eigo-Mt-Fuji
          committer_email: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          cwd:  '.'
          push: true
