name: SBI csv police for transform
on:
  push:
    paths:
      - 'downloads/sbi/*.csv'
jobs:
  sbi-csv-police:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: export csv destination path
        run: export PROCESSED_CSV_DEST_PATH=$(pwd)/src/data/fx_transactions/
        working-directory: ./

      - name: find and transform original SBI csv file 
        run: |
          echo $PROCESSED_CSV_DEST_PATH
          ls -la downloads/sbi/*.csv
          find downloads/sbi -name '*.csv' | sort | xargs -ITARGET python scripts/transform-sbi-csv.py TARGET $PROCESSED_CSV_DEST_PATH
        working-directory: ./

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
